### ISSUE TITLE
Tweak to fix span/badge positioning on Safari

### ISSUE THREAD

**Issue by jhargis** [jlizanab/FFolders#2]
This should correct the positioning of the folder span/badge on Safari (and IE, though I could not confirm since I don't have it at the moment)

``` css
    .ffolder span, .ffolder i{
        position: absolute;
        top: 50%;
        left: 50%;
        -o-transform: translate(-50%, -50%);
        -moz-transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        -webkit-transform: translate(-50%, -50%);
        transform: translate(-50%, -50%);
    }
```

BEFORE
![before](https://cloud.githubusercontent.com/assets/143113/18691919/81925584-7f4b-11e6-82fc-69259f21f341.png)

AFTER
![after](https://cloud.githubusercontent.com/assets/143113/18691956/b9d1029c-7f4b-11e6-812a-edfdca5c99a6.png)
